### ISSUE TITLE
Fix new links generation

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-resources#109]
Package version (if known): master (0.6.x)

## Describe the bug
New links generation 
- [x] doesn't account for aggregation filters, 
- [x] doesn't insert the "/api" prefix, 
- [x] self_html
- [x] publish
- [x] should fix pagination to not generate a next link if no next
(and I suspect ~~doesn't urlencode~~ urlencodes differently)

## Steps to Reproduce
1. Un skip the endpoint link tests in `test_pagination`/`test_resource_pagination` or `test_faceting`

## Expected behavior
Generated links always have: page, size, sort. Optionally have aggregations if passed in the first place

**Comment by lnielsen** [comment]
If the aggregations are in the ``params`` variable it should be rendered in the link.

**Comment by lnielsen** [comment]
The ``/api`` prefix should be added directly in the URI template I think.

**Comment by fenekku** [comment]
It's sad but URITemplate doesn't really work for us, because it doesn't recursively expand:

```python
route = URITemplate("/api/route/{?params*}")
route.expand({"params": {"a": [1,2]}})
# expect
# '/api/route/?a=1&a=2'
# get
# '/api/route/?a=%5B1%2C%202%5D'
```

and this is not really a bug: the [spec](https://tools.ietf.org/html/rfc6570#section-2.4.2) leaves it up to the implementation.

So... I will use another way :man_shrugging: ?

**Comment by fenekku** [comment]
In the end I added code in marshmallow-utils using uritemplate to manually sub-expand...

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/invenio-records-resources/pull/120 and others
