### ISSUE TITLE
re-enable search preference

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records-resources#122]
Package version (if known): v0.6.2

## Describe the bug

Search preference is not enabled and it could potentially lead to bouncing effect.

## Steps to Reproduce
1. see `services/records/service.py::search()`

## Additional context

It was disabled due to the lack of `user-agent` and `ip` related information. This info should be extracted and set in the `resource_requestctx`, then the resource should pass it to the service.

The old search object uses the `request` object https://github.com/inveniosoftware/invenio-search/blob/81f4d23a1f24fe0d1c2fb7b1a9c64fd7870daed3/invenio_search/api.py#L150 it should be migrated in a way that is not accessed and just passed https://github.com/inveniosoftware/invenio-search/blob/81f4d23a1f24fe0d1c2fb7b1a9c64fd7870daed3/invenio_search/api.py#L270

Values should be accessed at the resource level and passed to the service search? (maybe is the service who calculates the preference (hash) based on what the resource passes.

Why:
- https://github.com/inveniosoftware/invenio-search/pull/107
- https://www.elastic.co/guide/en/elasticsearch/guide/current/_search_options.html#_preference

**Comment by fenekku** [comment]
Blocked by merge + release of https://github.com/inveniosoftware/invenio-search/pull/207 first
