### ISSUE TITLE
Using DSL TermsFacets

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-resources#131]
Investigate if we can use https://elasticsearch-dsl.readthedocs.io/en/latest/faceted_search.html#facets instead of defining our own https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/records/search.py#L15

This might mean having to use FacetedSearch which might complicate things.

**Comment by ppanero** [comment]
We are already using [dsl.TermsFacets](https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/records/facets/facets.py#L71) and others. Is that what the issue was meant for? Can close?
