### ISSUE TITLE
tests: fix search tests

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-resources#19]
**Current**
Tests are not being cleaned correctly: indexes are not created/deleted properly. A fake index must be setup and `base_app` must be used rather than `app` in the fixtures. 

**Previous**
The get (search) endpoint is failing because the fetcher can't retrieve `'recid'` key from returned `data`:

```
invenio_resources/service/service.py:158: in search
    pid = cls.fetcher()(data=record, record_uuid=None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

record_uuid = None
data = {'_access': {'metadata_restricted': False, 'files_restricted': False}, '_owners': [1], '_created_by': 1, 'access_right...d title', 'type': 'Other', 'lang': 'eng'}], 'publication_date': '2020-07-08', '_publication_date_search': '2020-07-08'}

    def recid_fetcher(record_uuid, data):
        """Legacy way to fetch a record's identifiers.
    
        :param record_uuid: The record UUID.
        :param data: The record metadata.
        :returns: A :data:`invenio_pidstore.fetchers.FetchedPID` instance.
        """
        pid_field = current_app.config['PIDSTORE_RECID_FIELD']
        return FetchedPID(
            provider=RecordIdProvider,
            pid_type=RecordIdProvider.pid_type,
>           pid_value=str(data[pid_field]),
        )
E       KeyError: 'recid'

.venv/lib/python3.6/site-packages/invenio_pidstore/fetchers.py:67: KeyError
```

Needs investigation.

**Comment by ppanero** [comment]
Im pretty sure the fetcher works, is just the tests that do not clean the ES index if it was already existing...
Or it contains some data from old instances without `recid`...

My point being if the `data` has no `recid` field there is something really wrong on create/index. However, the fetcher has a correct behaviour.

**Comment by ppanero** [comment]
![Screenshot 2020-07-09 at 15 14 06](https://user-images.githubusercontent.com/6756943/87044522-eff2be00-c1f6-11ea-8084-58957a67e44e.png)


Tests are working fine on my PC (and travis) when starting from a scratch docker setup. So I would think there is something wrong with ES/DB. Might be the tests here are not properly cleaning?
