### ISSUE TITLE
Implement stubs for REST API endpoints

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-resources#22]
In Invenio-Records-Resources and Invenio-Drafts-Resources.

- [x] ``/records``: GET, POST
- [x] ``/records/:id``: GET, DELETE
- [x] ``/records/:id/versions`` GET, POST
- [x] ``/records/:id/files``: GET
- [x] ``/records/:id/files/:key`` GET
- [x] ``/records/:id/files/:key/download`` GET
- [x] ``/user/records`` GET
- [x] ``/records/:id/draft``: GET, POST, PUT, DELETE
- [x] ``/records/:id/draft/actions/:action``: POST
- [x] ``/records/:id/draft/files`` GET, POST, PUT, DELETE
- [x] ``/records/:id/draft/files/:key``: GET, PUT, DELETE
- [x] ``/records/:id/draft/files/:key/download`` GET

**Comment by fenekku** [comment]
Flask-resources doesn't currently support:

- `/records/:id/draft:` GET **and** POST (one **or** the other is possible)
- `/records/:id/draft/files` PUT, DELETE

**Comment by ppanero** [comment]
@fenekku what about the singleton resource? I think it does support all those no? Might need some work since it fell behind in changes I think.

In any case it does contain all the methods needed: https://github.com/inveniosoftware/flask-resources/blob/master/flask_resources/views/singleton.py

**Comment by fenekku** [comment]
For `/records/:id/draft/files` we could... but the semantics are getting weird

**Comment by fenekku** [comment]
but actually for the others it makes sense and moving some stuff around makes everything good potentially. Thanks @ppanero !

**Comment by fenekku** [comment]
Added update_all and delete_all to CollectionResource to make it possible and converted one of the CollectionResource to SingletonResource.

**Comment by fenekku** [comment]
PR for records stubs still pending: need to figure out /records url routing issue.
