### ISSUE TITLE
Link generation uses localhost  instead of 127.0.0.1 as host 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-resources#221]
Package version (if known): 0.14.1

## Describe the bug
It used to be that the host was defined via a config: `SITE_HOSTNAME` . Now, this config is ignored and link generation uses `localhost` (in development) as opposed to `127.0.0.1`:

```json
	"links": {
		"self": "https://localhost:5000/api/records/bszy6-r0664/draft",
		"self_html": "https://localhost:5000/uploads/bszy6-r0664",
		"files": "https://localhost:5000/api/records/bszy6-r0664/draft/files",
		"latest": "https://localhost:5000/api/records/bszy6-r0664/versions/latest",
		"latest_html": "https://localhost:5000/records/bszy6-r0664/latest",
		"publish": "https://localhost:5000/api/records/bszy6-r0664/draft/actions/publish",
		"versions": "https://localhost:5000/api/records/bszy6-r0664/versions",
		"access_links": "https://localhost:5000/api/records/bszy6-r0664/access/links"
	}
}
```

We need to align as otherwise running the application on 127.0.0.1:5000  (as we explicitly aligned towards in the past) will cause any API interaction e.g. on the deposit page, to not work because of browser rules/cross-site requests and all that.

## Steps to Reproduce
1. Run application on 127.0.0.1
2. Got to /uploads/new
3. Click on Save Draft

## Expected behavior
Align on localhost all the way or 127.0.0.1 all the way (might mean using the `SITE_HOSTNAME` config (we tried the flask config -`SERVERNAME` iirc- and it causes tons of issues with containers...

**Comment by lnielsen** [comment]
Fix it here (probably many tests will fail, but they can likely be fixed by setting the variables back to localhost in ``conftest.py``:

https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/config.py#L16-L18

**Comment by lnielsen** [comment]
Likely, this also means changes in Invenio-Drafts-Resources and Invenio-RDM-Records.

**Comment by fenekku** [comment]
Assigning it to @lnielsen to do the cascade of releases tomorrow (if no time, I will do it tomorrow).
