### ISSUE TITLE
validation and marshmallow

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records-resources#3]
@fenekku:

> **Serialization / Deserialization / Marshmallow**

>It dawns on me that marshmallow is both a record model (the fields + validation), a record serializer (json.py!), a loader (expects this shape)... There is a murkiness here, we might want to clear up by decree. We can say: here is what marshmallow will do for us and the things it won't.

**Comment by fenekku** [comment]
From discussions, this can be closed:

There are now 2 (well probably 3 :wink: ...) schemas:

1- At the API level. It converts and validates data coming from the outside.
2- (and 3-) At the pre-DB/ES level. It verifies that the converted data from the API conforms to the DB or ES expectations (and transforms it if need be - and need will be).
