### ISSUE TITLE
Create PID nested relation for funding

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-records-resources#325]
A new relation is needed in order to express  a `Funding` relationship as a pair of 

```
{
  'award': {},
  'funder': {}
}
```

Depends on: 

- `invenio-record-resources`: https://github.com/inveniosoftware/invenio-records-resources/pull/324
- `invenio-records`: https://github.com/inveniosoftware/invenio-records/pull/284
- `invenio-rdm-records`:  https://github.com/inveniosoftware/invenio-rdm-records/pull/939

**Comment by ppanero** [comment]
Not needed.
