### ISSUE TITLE
custom fields: can `relation_cls` be removed?

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records-resources#358]
Currently we are using this attribute [relation_cls](https://github.com/inveniosoftware/invenio-records-resources/blob/custom-fields/invenio_records_resources/services/custom_fields/base.py#L22) to be able to know when a custom field is a vocabulary and when it's not. Is there another way to avoid having this flag?

It is breaking the separation of concerns. Having a `relation_cls` attr here because of `invenio-vocabularies` generates a "theoretical" circular dependency, as in "it's making records-resources be aware of vocabularies" (even if does not require its installation).

**Comment by zzacharo** [comment]
Moved `relation_cls` to `VocabularyCF` for now. Checks are done on `getattr(cf, 'relation_cls', None)` to check if it's a vocabulary custom field or not
