### ISSUE TITLE
Define base implementation for notification builders and generators

### ISSUE THREAD

**Issue by rekt-hard** [inveniosoftware/invenio-records-resources#450]
For reasons of abstraction and reusability, a notification builder, filters, generators, and transformers shall be defined.

***Generator** takes care of creating a certain field of a notification and depends on the action/notification type. Therefore, one generator per notification field shall be defined.
- payload
- recipients

**RecipientFilter** takes care of removing users, which do not want to receive notifications based on the users preferences.

**RecipientBackendTransform** takes care of choosing the correct backend(s) for the user based on the users preferences.

**Notification** builder takes care of creating a notification based on the specified generators, filters and transformers. They shall specify the action/notification type.

```python
#
# Notification builder interface
#

# Invenio-Records-Resources/Invenio-Notifications
class PayloadGeneratorABC:

    def run(context: dict) -> dict:
        pass

class NotificationBuilderBase:
    
    def build(context: dict) -> Notification:
        pass

    payload_generator: List[PayloadGeneratorABC]
    recipients_generator: List[RecipientGeneratorABC]
    recipients_filters: List[PayloadGeneratorABC]
    recipient_backend_transform: List[PayloadGeneratorABC]
```

**Comment by ppanero** [comment]
Should have been closed on merge, seems GH hook didnt work
