### ISSUE TITLE
image processor should accept jp2 files

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/invenio-records-resources#483]
Out of the box RDM is configured to support JPEG200 files, however the files processor will not consider these (and thus not extract the metadata required) by default. 

https://github.com/inveniosoftware/invenio-records-resources/blame/ecdfff1d6a900fc638c687477d05ee8435a47a1b/invenio_records_resources/services/files/processors/image.py#L33

I'm happy to fix this, I guess to avoid dependency on anything RDM/IIIF related this list should be placed into a config variable and set to (the same values as) IIIF_SUPPORTED_FORMATS in app-rdm or invenio-records-rdm?

**Comment by ppanero** [comment]
I think it makes sense to make it configurable since the list might evolve over time (see case in point on jpg2000).
Since the metadata extractor lives in records-resources I'd make the config variable available here (e.g. `RECORDS_RESOURCES_IMAGE_FORMATS`. Would this work for previewer?
