### ISSUE TITLE
review response making functions

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-records-resources#5]
**problem**

It is not clear how the reponse building should treat links. The problem arises from the fact the needed attributes are not available in the places where it is needed (controller?)

**context**

@fenekku 
>I think these methods' responsibility is to wrap things up in Flask responses... but they also seem to be serializing with that links and prettyprint is that normal?

@ppanero prettyprint is part of the flask reponse. It specifies the tabbing.

The links, I assumed it would be part of the response no matter the type of serialization. Do we think that sort of answer (no links) would be used/needed?

Once this question is answered, we get into the separation of concerns. There we need to ask ourselves: Are links part of the record that goes in the response, or part of the response per se. IMHO, the second one, since is part of the REST paradigm.

**Comment by fenekku** [comment]
Yes. The kind of clarification we would like to know is : who is in charge of injecting links  ? We can try something and see...

**Comment by fenekku** [comment]
Link generation has been implemented. Link generators are defined the ServiceConfig.This can be closed.
