### ISSUE TITLE
Is "from" necessary in search URL args?

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-resources#57]
invenio-records-rest supported [a "from" query string parameter](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L460), but it seemed to be for legacy purposes. As such we didn't implement it in the new invenio-records-resources search functionality. Is that correct or should "from" be supported and if so what should its meaning be?

**Comment by lnielsen** [comment]
As discussed IRL, this is not a legacy feature, but something we added in v3.2 (see https://invenio.readthedocs.io/en/latest/releases/v3.2.0.html under "Records REST API improvements") to improve support for infinite scroll.
