### ISSUE TITLE
Search serialization returns None for "updated" and "created" fields

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-resources#72]
Package version (if known): 0.4.X

## Describe the bug

When performing a search on `/rdm-records` the returned hits have null values for `updated` and `created` fields.

## Steps to Reproduce
1. `/rdm-records`
2. Look at json results

```json

  "created": null,
  "updated": null,
```

## Expected behavior

These should have the UTC string of the respective updated nad created fields.

## Additional context

This breaks the search because there is string manipulation of the dates but they are javascript `null` at this point. The use of lodash's `_.get()` was not enough to prevent this problem because lodash tests on `undefined` (not a present field of value `null`).

**Comment by fenekku** [comment]
Related to: https://github.com/inveniosoftware/invenio-records-resources/issues/6

**Comment by lnielsen** [comment]
Fixed in sep branch
